# ============================================
# ; Title: Assignment 3.2 - Describing the Composer API
# ; File Name: kerrey-composers.yaml
# ; Author: Professor Krasso
# ; Date: 5 April 2022
# ; Modified By: Seth Kerrey
# ; Description:
# ;   Assignment to describe the Composer API using the OpenAPI Specification and YAML
# ; Resources:
# ;   Code was provided by Prof Krasso & Bellevue University 
# ===========================================

openapi: "3.0.0"
info:
  title: Composer API
  version: "1.0.0"
paths:
  /composers:
    get: #findAllComposers
      tags:
      - "composers"
      summary: Returns a list of composer documents
      description: |
        API for returning a list of composers from MongoDB Atlas
      operationId: "findAllComposers"
      responses: 
        "200":
          description: Composer Documents
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
    post: #createComposer
      tags:
        - "composers"
      summary: Creates a new composer object
      description: |
        API for adding new composer objects
      operationId: "createComposer"
      requestBody:
        description: Composer's information
        content:
          application/json:
            schema:
              required:
                - firstName
                - lastName
              properties:
                firstName:
                  description: |
                    Composer first name
                  type: string
                lastName: 
                  description: |
                    Composer last name
                  type: string
      responses:
        "200":
          description: User added
        "500":
          description: Server Exception
        "501": 
          description: MongoDB Exception
  /composers/{id}: 
    get: #findComposerById
      tags:
      - "composers"
      summary: Returns a composer document
      description: |
        API for returning a single composer object from MongoDB
      operationId: "findComposerById"
      parameters:
      - name: id
        in: "path"
        description: The composerId requested by the user
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Composer document in JSON format
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
        
 