# ============================================
# ; Title: Assignment 3.2 - Describing the Composer API
# ; File Name: kerrey-composers.yaml
# ; Author: Professor Krasso
# ; Date: 5 April 2022
# ; Modified By: Seth Kerrey
# ; Description:
# ;   Assignment to describe the Composer API using the OpenAPI Specification and YAML
# ; Resources:
# ;   Code was provided by Prof Krasso & Bellevue University 
# ===========================================